### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by Bloctans** [maxwolf8852/yolov7_package#1]
[ WARN:0@1.380] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('img.jpg'): can't open/read file: check file path/integrity
Fusing layers...
Traceback (most recent call last):
  File "C:\Users\me\Documents\GitHub\Python\python\justdance\testYOLO.py", line 7, in <module>
    classes, boxes, scores = det.detect(img)
  File "D:\Program Files\Python\lib\site-packages\yolov7_package\model_utils.py", line 187, in detect
    img_inf = cv2.resize(img, self.img_size)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src data type = 17 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by Bloctans** [comment]
im stupid as hell

**Comment by romirk** [comment]
hi, how did you solve this? (@Bloctans)
