### ISSUE TITLE
Camera tracking seems to be very slow

### ISSUE THREAD

**Issue by Bloctans** [maxwolf8852/yolov7_package#2]
I don't know if I'm having a moment where I'm stupid or something but for some reason this seems very slow

Here is my code:

```python
from yolov7_package import Yolov7Detector
import cv2

if __name__ == '__main__':
    cap = cv2.VideoCapture(0)
    det = Yolov7Detector(traced=False)
    while cap.isOpened():
        success, img = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            continue

        classes, boxes, scores = det.detect(img)
        img = det.draw_on_image(img, boxes[0], scores[0], classes[0])

        cv2.imshow('MediaPipe Pose', cv2.flip(img, 1))
        if cv2.waitKey(5) & 0xFF == 27:
            break

    cap.release()
```

**Comment by maxwolf8852** [comment]
- Which version of pytorch are you using (cpu/cuda)? [you can check it with "torch.cuda.is_available()"]
- If you are trying to perform camera tracking without gpu, you can try setting the 'tiny' parameter to use a smaller model with less accuracy but faster execution speed, e.g. `det = Yolov7Detector(traced=False, weights='yolov7-tiny.pt')`

**Comment by Bloctans** [comment]
i dont know if i have cuda

**Comment by Bloctans** [comment]
nope, no cuda

**Comment by Bloctans** [comment]
tiny is still pretty slow i have an i5-9300H with a gtx 1650 and intel uhd 630

**Comment by maxwolf8852** [comment]
Try to install pytorch with cuda enabled, it will greatly increase your performance. To do this, you need to install the СUDA toolkit and CUDNN library from the NVidia official website.Then, reinstall pytorch  to achieve `torch.cuda.is_available() == True`

**Comment by maxwolf8852** [comment]
How long does it take to perform image processing with `det.detect(img)` call? E.g. in Apple M1 Pro cpu it takes ~150 ms, that is not realtime. If you want to have fast processing, use CUDA support.

**Comment by maxwolf8852** [comment]
Also, you can try python mpire/multiprocessing library to parallel processing task
